const ADD_DEPOSIT = 'transactions/ADD_DEPOSIT'
const ADD_EXPENSE = 'transactions/ADD_EXPENSE'
const ADD_NOTIFICATION = 'transactions/ADD_NOTIFICATION'
const CLOSE_NOTIFICATION = 'transactions/CLOSE_NOTIFICATION'

const FETCH_TRANSACTIONS = 'transactions/FETCH_TRANSACTIONS'
const FETCH_TRANSACTIONS_COMPLETED = 'transactions/FETCH_TRANSACTIONS_COMPLETED'
const FETCH_TRANSACTIONS_FAILED = 'transactions/FETCH_TRANSACTIONS_FAILED'

export default {
  ADD_DEPOSIT,
  ADD_EXPENSE,

  FETCH_TRANSACTIONS,
  FETCH_TRANSACTIONS_COMPLETED,
  FETCH_TRANSACTIONS_FAILED,

  ADD_NOTIFICATION,
  CLOSE_NOTIFICATION
}
